services:
  - type: web
    name: astrology-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
      - key: NOTIFY_PASS
        sync: false
      - key: RECEIVER_EMAIL 
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: PORT
        value: "5000"
